modLoader = "javafml"
loaderVersion = "[${forge},)"
issueTrackerURL = "https://github.com/rhysdh540/createunlimited/issues"
license = "GPL-3.0"

[[mods]]
modId = "createunlimited"
version = "${version}"
displayName = "Create Unlimited"
authors = "rdh"
description = '''
Remove all the limits!
'''
logoFile = "icon.png"

[[dependencies.createunlimited]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createunlimited]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createunlimited]]
modId="create"
mandatory=true
versionRange="[${create_forge},)"
ordering="NONE"
side="BOTH"