name: build
on: [ pull_request, push ]

jobs:
    build:
        if: "!startsWith(github.event.head_commit.message, '[skip]')"
        strategy:
            matrix:
                java: [ 17 ]
        runs-on: ubuntu-latest
        steps:

            - name: steal code from repository
              uses: actions/checkout@v2

            - name: setup jdk ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}

            - name: cache gradle
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle

            - name: give gradle permission to murder github servers
              run: chmod +x ./gradlew

            - name: gradle murders github servers (1.19.2)
              run: ./gradlew assemble -PmcVer="1.19.2"

            - name: gradle murders github servers (1.20.1)
              run: ./gradlew assemble -PmcVer="1.20.1"

            - name: upload forge build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: cu-artifacts-forge
                  path: forge/build/libs/*.jar

            - name: upload fabric build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: cu-artifacts-fabric
                  path: fabric/build/libs/*.jar

            - name: upload merged build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: cu-artifacts-merged
                  path: |
                      build/libs/merged/*.jar